In [10]:
import numpy as  np
from numpy import linalg as LA
arr2d = np.array((
    (100, 200, 300),
    (111, 222, 3333),
    (129,461, 795)
))
#计算矩阵的特征值和特征向量。
eig_val, eig_vec = LA.eig(arr2d)
print("eig_val=" ,eig_val, "\neig_vec=", eig_vec)

#计算矩阵范数
LA.norm(arr2d)
#计算数组的行列式。
LA.det(arr2d)
#计算矩阵的逆矩阵。
LA.inv(arr2d)

arr1 = np.array([[2,3], [3,4]])
arr2 = np.array([4, 5])
#求解线性矩阵方程或线性标量方程组。
#计算明确确定的，即满秩线性矩阵方程 ax = b 的“精确”解 x。
x = np.linalg.solve(arr1, arr2)
print("x=", x)
np.allclose(np.dot(arr1, x), arr2)

eig_val= [1822.51339301   44.55008575 -750.06347876] 
eig_vec= [[-0.17665845 -0.97063324  0.12766721]
 [-0.88955706  0.23976762 -0.95328385]
 [-0.4212838   0.01956002  0.27377178]]


3488.7936310421114

-60899999.99999991

array([[ 2.23320690e-02,  3.39901478e-04, -9.85221675e-03],
       [-5.61103448e-03, -6.69950739e-04,  4.92610837e-03],
       [-3.70000000e-04,  3.33333333e-04, -8.50138220e-20]])

x= [-1.  2.]


True